#Basic Numpy

##Numpy stands for numerical python

####The starring role is played by the "ndarray"
####The numpy library also provides linear algebra routines
####Pandas is built on numpy
####There is overlap in what numpy provides, in terms of data analysis capabilities

In [1]:
#The standard way to import the numpy library
import numpy as np

#Constructing

In [ ]:
#TODO create a python list to hold the following numbers 3, 4.7, 2, 0, 1.2, 1
#TODO convert the python list to an ndarry using the "np.array()" method

In [ ]:
#TODO using the shape attribute print out the shape of the ndarray you created
#TODO using the dtype attribute print out the type of the ndarray you created

In [ ]:
#TODO create a second list of numbers 2, 3.4, 3.3, 6, 2, 1
#TODO in python create a new list which contains the 2 lists of numbers
#TODO convert this list of lists into a 2 dimensionl ndarray
#TODO confirm the dimensionality of the array using the ndim attribute, also print out the shape and type

####There are a number of helper functions to create arrays from scratch

In [ ]:
#TODO using the np.zeros and np.ones methods create 4 ndarrays, 2 of type int, 2 of type float 
#hint: there is a dtype option within the array method that can be used to set the type

####It is often necessary to recast data types from one type to another, as we will see with the upcoming exploratory data analysis work

In [10]:
#TODO using the built in method astype convert one of the numerica arrays into an array of strings
#TODO confirm that the new array really is of dtype string

##Question: Does astype create a new copy of the array?

####Often when you read datasets from file numbers get read as strings

In [ ]:
#TODO convert the array of strings back to floats

In [ ]:
#TODO what does the np.arange do
#TODO create an integer array containing 20 integers, starting at 50 and going up in steps of 2

#Vectorization

In [ ]:
#TODO create a 2 by 3 array of floats - use the array you created above or create new ones

In [ ]:
#TODO produce an array of the squares of all the numbers
#TODO produce an array of the sum of all the numbers
#TODO produce an array where all the numbers are multiplied by 4.3

##Question what is the difference between vectorization and broadcasting

#Basic Indexing, Slicing and Dicing

In [ ]:
#TODO using the array of 20 integers you created above find:
#The 5th element
#The 5th to 8th elements inclusive

In [ ]:
#TODO multiply the 5th to 8th elements by 5.6
#TODO now print the original array in full

##Question: What do you notice about the changes you made to the slice?

In [ ]:
#TODO This time make a slice by using the 'copy' method
#TODO Multiply this by 0.5
#TODO print the original array

####This is the difference between a view and a copy

In [ ]:
#TODO using the array of 20 integers slice the array from the begining to the 10th element
#TODO now slice it from the 4th element to the end
#TODO assign 32 to all the elements of the slice
#TODO print the original array

##Sorting

In [22]:
a = np.array([4, 5, 2, 8, 1])
#TODO using the built in sort method to sort this array
#TODO confirm the array has been sorted by printing out the array

[1 2 4 5 8]


In [34]:
a = np.array([[4, 3, 29], [8, 6, 11]])
#TODO print the shape of this multi-dimensional array
#TODO print the array an sort each row, reprint the array to confirm

a = np.array([[4, 3, 29], [8, 6, 11]])
#TODO now sort by columns

##NP arrays as sets

In [35]:
names = np.array(['Jim', 'John', 'Bill', 'Tony', 'Jim', 'Bill', 'Daniel', 'Jim'])
#TODO print out just the unique names in this nd array

#Random Number Generation

Here is a linkg to the documentation for the random sampling routines built into numpy http://docs.scipy.org/doc/numpy/reference/routines.random.html#

These are incredibly useful and powerful

In [16]:
#TODO using np.random.rand create an array of 10 random numbers

array([ 0.26390037,  0.45393603,  0.8756755 ,  0.58581299,  0.39711853,
        0.84202509,  0.7938514 ,  0.97158642,  0.85151365,  0.48682389])

#Universal Functions

####A function that performs elementwise operation on the data in an nddarray.

In [ ]:
#TODO using the random number array you created above caluclate the following for all the elements of the array:
#the square root
#the absolute value

In [ ]:
#TOD create a boolean array by checking that each element of the array is "not a number

##Mathematical and Statistical Methods

In [ ]:
#TODO create an array of 1000 normally distributed numbers (standard normal distribution)

In [41]:
#TODO get the mean, sum, standard deviation, and cumulative sum

-0.037371497628945732

In [ ]:
##Question: To calculate standard deviation does np.std() use 1/N or 1/(N-1)

In [53]:
#TODO write no more than 4 lines of code to justify your answer

##Meshgrid

In [78]:
points = np.arange(-1, 2, 1)
print "points is an array of  ", len(points), "points:", points

#To create a meshgrid we would therefore need a total of 9 points in a grid, 3 along an x axis and 3 along a y axis
x, y = np.meshgrid(points, points)

print "the x axis points are\n", x
print "the y axis points are\n", y

print "The individual pairs of points could be generated like this:"

for i in np.arange(len(points)):
    for j in np.arange(len(points)):
        print "(", x[i][j], ",", y[i][j], ")",

points is an array of   3 points: [-1  0  1]
the x axis points are
[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]
the y axis points are
[[-1 -1 -1]
 [ 0  0  0]
 [ 1  1  1]]
The individual pairs of points could be generated like this:
( -1 , -1 ) ( 0 , -1 ) ( 1 , -1 ) ( -1 , 0 ) ( 0 , 0 ) ( 1 , 0 ) ( -1 , 1 ) ( 0 , 1 ) ( 1 , 1 )


####Meshgrad is useful for 3d plotting